class_name ArgValue

enum {
	USUAL = 0, 
	VALUE = 1, 
	KEY = 2, 
	UNIQUE_WEAPONS = 3, 
	ADDITIONAL_WEAPONS = 4, 
	TIER = 5, 
	SCALING_STAT = 6, 
	SCALING_STAT_VALUE = 7, 
	MAX_NB_OF_WAVES = 8, 
	TIER_IV_WEAPONS = 9, 
	TIER_I_WEAPONS = 10, 
	ABS_VALUE = 11
}
