class_name LoadStatus

enum {SAVE_OK, SAVE_MISSING, CORRUPTED_SAVE, CORRUPTED_SAVE_LATEST, CORRUPTED_ALL_SAVES, 
	CORRUPTED_ALL_SAVES_STEAM, CORRUPTED_ALL_SAVES_NO_STEAM, 
	CORRUPTED_ALL_SAVES_EPIC, CORRUPTED_ALL_SAVES_NO_EPIC}
